name: ci
on: push
jobs:
  test:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Switch Xcode to 12.0.1
        run: xcversion select 12.0.1
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
