name: CI

on: push

jobs:
  test:
    runs-on: macos-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Test
        run: swift test
